### ISSUE TITLE
Internal error - Crash

### ISSUE THREAD

**Issue by sviraaj** [chipsalliance/firrtl#2583]
### Checklist

- [ ] Did you specify the current behavior?
- [ ] Did you specify the expected behavior?
- [ ] Did you provide a code example showing the problem?
- [ ] Did you describe your environment?
- [ ] Did you specify relevant external information?

### What is the current behavior?

[error] (run-main-0) firrtl.FirrtlInternalException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error] firrtl.FirrtlInternalException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error]         at firrtl.Utils$.error(Utils.scala:453)
[error]         at firrtl.Utils$.throwInternalError(Utils.scala:166)
[error]         at firrtl.stage.phases.CatchExceptions.transform(CatchExceptions.scala:33)
[error]         at firrtl.stage.phases.CatchExceptions.transform(CatchExceptions.scala:13)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:37)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:240)
[error]         at firrtl.options.Translator.transform$(Phase.scala:240)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:262)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:86)
[error]         at firrtl.options.DependencyManager.transform(DependencyManager.scala:255)
[error] Caused by: scala.ScalaReflectionException: type LegalizeClocksTransform is not a class
[error]         at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:272)
[error]         at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:272)
[error]         at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:94)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala1(JavaMirrors.scala:1031)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$classToScala$1(JavaMirrors.scala:986)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:98)
[error]         at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:38)
[error]         at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:96)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:986)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:197)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.symbol(JavaMirrors.scala:235)
[error]         at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.symbol(JavaMirrors.scala:234)
[error]         at firrtl.options.Dependency$.isSingleton(Phase.scala:37)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 35 s, completed 7 Dec, 2022 7:43:02 PM

### What is the expected behavior?
Elaboration successful

### Your environment

- Chisel Verions: latest
- sbt: 1.4.9
- OS: Linux space 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Verilator version: Verilator 4.202 2021-04-24 rev v4.202

**Comment by ekiwi** [comment]
Could you share your source code with us?
